# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               VikiTravels
tagline:             '| My Travel Tales ..'
description:         'A Collection of my Travel Tales and itineraries' 
url:                 https://vikitravels.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Vikas Pandey
  url:               https://www.facebook.com/profile.php?id=694230814
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
